"""compnay_users

Revision ID: 0d971b57f575
Revises: 810a4dd7cd66
Create Date: 2023-03-10 09:26:51.625697

"""
from alembic import op
import sqlalchemy as sa
import databases


# revision identifiers, used by Alembic.
revision = '0d971b57f575'
down_revision = '810a4dd7cd66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('compnay_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compnay_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_users')
    # ### end Alembic commands ###
