"""records

Revision ID: 33877d82ab2d
Revises: 3756bd33b69a
Create Date: 2023-03-25 14:25:57.157123

"""
from alembic import op
import sqlalchemy as sa
import databases


# revision identifiers, used by Alembic.
revision = '33877d82ab2d'
down_revision = '3756bd33b69a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('quizz_id', sa.Integer(), nullable=False),
    sa.Column('average_result', sa.Float(), nullable=True),
    sa.Column('questions', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['quizz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('answers')
    op.add_column('company_members', sa.Column('questions', sa.Integer(), nullable=True))
    op.add_column('company_members', sa.Column('correct', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('question_numb', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('answers', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('questions', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('correct', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'correct')
    op.drop_column('users', 'questions')
    op.drop_column('questions', 'answers')
    op.drop_column('questions', 'question_numb')
    op.drop_column('company_members', 'correct')
    op.drop_column('company_members', 'questions')
    op.create_table('answers',
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='answers_question_id_fkey', ondelete='CASCADE')
    )
    op.drop_table('records')
    # ### end Alembic commands ###
