"""a

Revision ID: 41234d78ddd8
Revises: c2d1512dd510
Create Date: 2023-03-15 09:07:09.866171

"""
from alembic import op
import sqlalchemy as sa
import databases


# revision identifiers, used by Alembic.
revision = '41234d78ddd8'
down_revision = 'c2d1512dd510'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_members', sa.Column('company_id', sa.Integer(), nullable=False))
    op.drop_constraint('company_members_compnay_id_fkey', 'company_members', type_='foreignkey')
    op.create_foreign_key(None, 'company_members', 'companies', ['company_id'], ['id'])
    op.drop_column('company_members', 'compnay_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_members', sa.Column('compnay_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'company_members', type_='foreignkey')
    op.create_foreign_key('company_members_compnay_id_fkey', 'company_members', 'companies', ['compnay_id'], ['id'])
    op.drop_column('company_members', 'company_id')
    # ### end Alembic commands ###
