"""answers

Revision ID: 5026dd9e7238
Revises: fda894ad4495
Create Date: 2023-03-22 09:12:07.720695

"""
from alembic import op
import sqlalchemy as sa
import databases


# revision identifiers, used by Alembic.
revision = '5026dd9e7238'
down_revision = 'fda894ad4495'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'answers')
    # ### end Alembic commands ###
