"""staistics

Revision ID: 9e04b87d51f9
Revises: fb34e739f1dc
Create Date: 2023-03-19 15:24:01.532460

"""
from alembic import op
import sqlalchemy as sa
import databases


# revision identifiers, used by Alembic.
revision = '9e04b87d51f9'
down_revision = 'fb34e739f1dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('quizz_id', sa.Integer(), nullable=False),
    sa.Column('average_result', sa.Integer(), nullable=True),
    sa.Column('questions', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['quizz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('record')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quizz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_result', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('questions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='record_company_id_fkey'),
    sa.ForeignKeyConstraint(['quizz_id'], ['quizzes.id'], name='record_quizz_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='record_user_id_fkey')
    )
    op.drop_table('records')
    # ### end Alembic commands ###
