"""a

Revision ID: ce8f23a1e7fb
Revises: 24d90106f9da
Create Date: 2023-03-24 12:49:04.609641

"""
from alembic import op
import sqlalchemy as sa
import databases


# revision identifiers, used by Alembic.
revision = 'ce8f23a1e7fb'
down_revision = '24d90106f9da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_numb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_numb')
    # ### end Alembic commands ###
