"""a

Revision ID: ea4391631a6e
Revises: 41234d78ddd8
Create Date: 2023-03-15 09:12:53.782099

"""
from alembic import op
import sqlalchemy as sa
import databases


# revision identifiers, used by Alembic.
revision = 'ea4391631a6e'
down_revision = '41234d78ddd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_members', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_members', 'id')
    # ### end Alembic commands ###
