"""staistics

Revision ID: fb34e739f1dc
Revises: 3756bd33b69a
Create Date: 2023-03-19 15:21:19.868131

"""
from alembic import op
import sqlalchemy as sa
import databases


# revision identifiers, used by Alembic.
revision = 'fb34e739f1dc'
down_revision = '3756bd33b69a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('quizz_id', sa.Integer(), nullable=False),
    sa.Column('average_result', sa.Integer(), nullable=True),
    sa.Column('questions', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['quizz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('company_members', sa.Column('questions', sa.Integer(), nullable=True))
    op.add_column('company_members', sa.Column('correct', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('questions', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('correct', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'correct')
    op.drop_column('users', 'questions')
    op.drop_column('company_members', 'correct')
    op.drop_column('company_members', 'questions')
    op.drop_table('record')
    # ### end Alembic commands ###
