"""staistics

Revision ID: fda894ad4495
Revises: 9e04b87d51f9
Create Date: 2023-03-19 15:53:17.765445

"""
from alembic import op
import sqlalchemy as sa
import databases


# revision identifiers, used by Alembic.
revision = 'fda894ad4495'
down_revision = '9e04b87d51f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
