services:
  backend:
    build: .
    command: python app/main.py
    volumes:
      - ./:/usr/src/backend/
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - ${POSTGRES_PORT}:${P_PORT}
volumes:
  postgres_data: