services:
  backend:
    build: .
    command: python app/main.py
    volumes:
      - ./:/usr/src/backend/
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  celery:
    build: .
    command: celery -A app.celery_base beat -l DEBUG
    volumes:
      - ./:/usr/src/backend/
    env_file:
      - ./.env
    depends_on:
      - redis
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  db_test:
    image: postgres:15.1
    env_file:
      - ./.env.db
    ports:
      - ${POSTGRES_PORT_TEST}:${POSTGRES_PORT_TEST}
volumes:
  postgres_data: