name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  run_tests:
      runs-on: ubuntu-latest
      env:
        HOST: 0.0.0.0
        PORT: 80
        SQLALCHEMY_SILENCE_UBER_WARNING: 1
        DATABASE_URL: postgresql+asyncpg://postgres:postgres@db/app_db
        DATABASE_URL_TEST: postgresql+asyncpg://postgres:postgres@db_test/app_db
        REDIS_URL: redis://redis:6379/0
        REDIS_PORT: 6379
        SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
        DOMAIN: dev-wvvxa6vlw7mfytea.eu.auth0.com
        API_AUDIENCE: https://meduzzen_internship
        ALGORITHM_AUTH_2: HS256
        ALGORITHM_AUTH_0: RS256
        ISSUER: https://dev-wvvxa6vlw7mfytea.eu.auth0.com/
        JWKS_URL: https://dev-wvvxa6vlw7mfytea.eu.auth0.com/.well-known/jwks.json
      services:
        postgres:
          image: postgres:15.1
          env:
            POSTGRES_DB: app_db
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_PORT: 5434
          ports:
            - 5434:5434
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        redis:
          image: redis:latest
          ports:
            - 6379:6379
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
            cache: 'pip'
        - name: install dependencies
          run: |
            pip install -r requirements.txt
        - name: run tests
          run: |
            pytest -vv -n auto app
